<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="temperature" nsURI="http://jena.de/mdo/model/sensore/rest/1.0"
    nsPrefix="temperature">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="resource" value="platform:/resource/de.jena.mdo.sensinact.resource.model/model/resource.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TempSensore" eSuperTypes="http://jena.de/sensinact/model/resource#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
