/*
 */
package de.jena.mdo.ibis.devicemanagementservice;

import de.jena.mdo.ibis.common.IBISIPAnyURI;
import de.jena.mdo.ibis.common.IBISIPDateTime;
import de.jena.mdo.ibis.common.IBISIPNMTOKEN;
import de.jena.mdo.ibis.common.IBISIPUnsignedLong;

import org.eclipse.emf.ecore.EObject;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device Management Service Install Update Request Structure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateID <em>Update ID</em>}</li>
 *   <li>{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateTimestamp <em>Update Timestamp</em>}</li>
 *   <li>{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateURL <em>Update URL</em>}</li>
 *   <li>{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateFileChecksum <em>Update File Checksum</em>}</li>
 *   <li>{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateFileSize <em>Update File Size</em>}</li>
 * </ul>
 *
 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure()
 * @model extendedMetaData="name='DeviceManagementService.InstallUpdateRequestStructure' kind='elementOnly'"
 * @generated
 */
@ProviderType
public interface DeviceManagementServiceInstallUpdateRequestStructure extends EObject {
	/**
	 * Returns the value of the '<em><b>Update ID</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Unique id generated by the controller to identify an update job
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Update ID</em>' containment reference.
	 * @see #setUpdateID(IBISIPNMTOKEN)
	 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure_UpdateID()
	 * @model containment="true" required="true"
	 *        extendedMetaData="kind='element' name='UpdateID' namespace='##targetNamespace'"
	 * @generated
	 */
	IBISIPNMTOKEN getUpdateID();

	/**
	 * Sets the value of the '{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateID <em>Update ID</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Update ID</em>' containment reference.
	 * @see #getUpdateID()
	 * @generated
	 */
	void setUpdateID(IBISIPNMTOKEN value);

	/**
	 * Returns the value of the '<em><b>Update Timestamp</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Timestamp used for GetUpdateHistory and RetrieveUpdateState responses and for logging
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Update Timestamp</em>' containment reference.
	 * @see #setUpdateTimestamp(IBISIPDateTime)
	 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure_UpdateTimestamp()
	 * @model containment="true" required="true"
	 *        extendedMetaData="kind='element' name='UpdateTimestamp' namespace='##targetNamespace'"
	 * @generated
	 */
	IBISIPDateTime getUpdateTimestamp();

	/**
	 * Sets the value of the '{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateTimestamp <em>Update Timestamp</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Update Timestamp</em>' containment reference.
	 * @see #getUpdateTimestamp()
	 * @generated
	 */
	void setUpdateTimestamp(IBISIPDateTime value);

	/**
	 * Returns the value of the '<em><b>Update URL</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * URL from which the device shall download the update file
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Update URL</em>' containment reference.
	 * @see #setUpdateURL(IBISIPAnyURI)
	 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure_UpdateURL()
	 * @model containment="true" required="true"
	 *        extendedMetaData="kind='element' name='UpdateURL' namespace='##targetNamespace'"
	 * @generated
	 */
	IBISIPAnyURI getUpdateURL();

	/**
	 * Sets the value of the '{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateURL <em>Update URL</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Update URL</em>' containment reference.
	 * @see #getUpdateURL()
	 * @generated
	 */
	void setUpdateURL(IBISIPAnyURI value);

	/**
	 * Returns the value of the '<em><b>Update File Checksum</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Optional checksum of update file
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Update File Checksum</em>' containment reference.
	 * @see #setUpdateFileChecksum(ChecksumStructure)
	 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure_UpdateFileChecksum()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='UpdateFileChecksum' namespace='##targetNamespace'"
	 * @generated
	 */
	ChecksumStructure getUpdateFileChecksum();

	/**
	 * Sets the value of the '{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateFileChecksum <em>Update File Checksum</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Update File Checksum</em>' containment reference.
	 * @see #getUpdateFileChecksum()
	 * @generated
	 */
	void setUpdateFileChecksum(ChecksumStructure value);

	/**
	 * Returns the value of the '<em><b>Update File Size</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Optional size of update file
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Update File Size</em>' containment reference.
	 * @see #setUpdateFileSize(IBISIPUnsignedLong)
	 * @see de.jena.mdo.ibis.devicemanagementservice.IbisDeviceManagementServicePackage#getDeviceManagementServiceInstallUpdateRequestStructure_UpdateFileSize()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='UpdateFileSize' namespace='##targetNamespace'"
	 * @generated
	 */
	IBISIPUnsignedLong getUpdateFileSize();

	/**
	 * Sets the value of the '{@link de.jena.mdo.ibis.devicemanagementservice.DeviceManagementServiceInstallUpdateRequestStructure#getUpdateFileSize <em>Update File Size</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Update File Size</em>' containment reference.
	 * @see #getUpdateFileSize()
	 * @generated
	 */
	void setUpdateFileSize(IBISIPUnsignedLong value);

} // DeviceManagementServiceInstallUpdateRequestStructure
