<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deviceModel" nsURI="http://smartmodels.com/deviceModel/1.0"
    nsPrefix="deviceModel">
  <eClassifiers xsi:type="ecore:EClass" name="DeviceModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This entity captures the static properties of a Device. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An alternative name for this item"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brandName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Device's brand name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" upperBound="-1"
        eType="#//DeviceModelCategoryValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The color of the product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlledProperty" upperBound="-1"
        eType="#//DeviceModelControlledPropertyValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataProvider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A sequence of characters identifying the provider of the harmonised data entity."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateCreated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Entity creation timestamp. This will usually be allocated by the storage platform."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp of the last modification of the entity. This will usually be allocated by the storage platform."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A description of this item"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceClass" eType="#//DeviceModelDeviceClassValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Class of constrained device as specified by RFC 7228. If the device is not a constrained device this property shall not be present. Normative References: [RFC7228](https://tools.ietf.org/html/rfc7228#section-3). Enum:'C0, C1, C2'"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A link to device's documentation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyLimitationClass"
        eType="#//DeviceModelEnergyLimitationClassValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Device's class of energy limitation as per RFC 7228. Normative References: [RFC7228](https://tools.ietf.org/html/rfc7228#page-11). Enum:'E0, E1, E2, E9'"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" upperBound="-1"
        eType="#//DeviceModelFunctionValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique identifier of the entity"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An image of the item"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The MAC address of the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manufacturerName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Device's manufacturer name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Device's model name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of this item."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedProtocol" upperBound="-1"
        eType="#//DeviceModelSupportedProtocolValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedUnits" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DeviceModelTypeValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NGSI Entity type. it has to be DeviceModel"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelCategoryValue">
    <eLiterals name="actuator"/>
    <eLiterals name="beacon" value="1"/>
    <eLiterals name="endgun" value="2"/>
    <eLiterals name="HVAC" value="3"/>
    <eLiterals name="implement" value="4"/>
    <eLiterals name="irrSection" value="5"/>
    <eLiterals name="irrSystem" value="6"/>
    <eLiterals name="meter" value="7"/>
    <eLiterals name="multimedia" value="8"/>
    <eLiterals name="network" value="9"/>
    <eLiterals name="sensor" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelControlledPropertyValue">
    <eLiterals name="airPollution"/>
    <eLiterals name="atmosphericPressure" value="1"/>
    <eLiterals name="averageVelocity" value="2"/>
    <eLiterals name="batteryLife" value="3"/>
    <eLiterals name="batterySupply" value="4"/>
    <eLiterals name="cdom" value="5"/>
    <eLiterals name="conductance" value="6"/>
    <eLiterals name="conductivity" value="7"/>
    <eLiterals name="depth" value="8"/>
    <eLiterals name="eatingActivity" value="9"/>
    <eLiterals name="electricityConsumption" value="10"/>
    <eLiterals name="energy" value="11"/>
    <eLiterals name="fillingLevel" value="12"/>
    <eLiterals name="freeChlorine" value="13"/>
    <eLiterals name="gasConsumption" value="14"/>
    <eLiterals name="gateOpening" value="15"/>
    <eLiterals name="heading" value="16"/>
    <eLiterals name="humidity" value="17"/>
    <eLiterals name="light" value="18"/>
    <eLiterals name="location" value="19"/>
    <eLiterals name="milking" value="20"/>
    <eLiterals name="motion" value="21"/>
    <eLiterals name="movementActivity" value="22"/>
    <eLiterals name="noiseLevel" value="23"/>
    <eLiterals name="occupancy" value="24"/>
    <eLiterals name="orp" value="25"/>
    <eLiterals name="pH" value="26"/>
    <eLiterals name="power" value="27"/>
    <eLiterals name="precipitation" value="28"/>
    <eLiterals name="pressure" value="29"/>
    <eLiterals name="refractiveIndex" value="30"/>
    <eLiterals name="salinity" value="31"/>
    <eLiterals name="smoke" value="32"/>
    <eLiterals name="soilMoisture" value="33"/>
    <eLiterals name="solarRadiation" value="34"/>
    <eLiterals name="speed" value="35"/>
    <eLiterals name="tds" value="36"/>
    <eLiterals name="temperature" value="37"/>
    <eLiterals name="trafficFlow" value="38"/>
    <eLiterals name="tss" value="39"/>
    <eLiterals name="turbidity" value="40"/>
    <eLiterals name="waterConsumption" value="41"/>
    <eLiterals name="waterFlow" value="42"/>
    <eLiterals name="waterLevel" value="43"/>
    <eLiterals name="waterPollution" value="44"/>
    <eLiterals name="weatherConditions" value="45"/>
    <eLiterals name="weight" value="46"/>
    <eLiterals name="windDirection" value="47"/>
    <eLiterals name="windSpeed" value="48"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelDeviceClassValue">
    <eLiterals name="C0"/>
    <eLiterals name="C1" value="1"/>
    <eLiterals name="C2" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelEnergyLimitationClassValue">
    <eLiterals name="E0"/>
    <eLiterals name="E1" value="1"/>
    <eLiterals name="E2" value="2"/>
    <eLiterals name="E9" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelFunctionValue">
    <eLiterals name="levelControl"/>
    <eLiterals name="sensing" value="1"/>
    <eLiterals name="onOff" value="2"/>
    <eLiterals name="openClose" value="3"/>
    <eLiterals name="metering" value="4"/>
    <eLiterals name="eventNotification" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelSupportedProtocolValue">
    <eLiterals name="3g"/>
    <eLiterals name="bluetooth" value="1"/>
    <eLiterals name="bluetooth LE" value="2"/>
    <eLiterals name="cat-m" value="3"/>
    <eLiterals name="coap" value="4"/>
    <eLiterals name="ec-gsm-iot" value="5"/>
    <eLiterals name="gprs" value="6"/>
    <eLiterals name="http" value="7"/>
    <eLiterals name="lwm2m" value="8"/>
    <eLiterals name="lora" value="9"/>
    <eLiterals name="lte-m" value="10"/>
    <eLiterals name="mqtt" value="11"/>
    <eLiterals name="nb-iot" value="12"/>
    <eLiterals name="onem2m" value="13"/>
    <eLiterals name="sigfox" value="14"/>
    <eLiterals name="ul20" value="15"/>
    <eLiterals name="websocket" value="16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceModelTypeValue">
    <eLiterals name="DeviceModel"/>
  </eClassifiers>
</ecore:EPackage>
