<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="system_hours" nsURI="http://smartmodels.com/system_hours/1.0"
    nsPrefix="system_hours">
  <eClassifiers xsi:type="ecore:EClass" name="system_hours">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the system hours of operation. According to the Standard GBFS 2.2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Array that contains system hours of operations."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique identifier of the entity"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_updated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Last time the data in the feed was updated in POSIX time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ttl" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//system_hoursTypeValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NGSI entity type. It has to be system_hours"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="#//system_hoursVersionValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Array that contains system hours of operations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rental_hours" upperBound="-1"
        eType="#//Rental_hours" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rental_hours">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="days" lowerBound="1" upperBound="7"
        eType="#//Rental_hoursDaysValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="End time for the hours of operation of the system."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Start time for the hours of operation of the system."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user_types" lowerBound="1"
        upperBound="2" eType="#//Rental_hoursUser_typesValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Rental_hoursDaysValue">
    <eLiterals name="sun"/>
    <eLiterals name="mon" value="1"/>
    <eLiterals name="tue" value="2"/>
    <eLiterals name="wed" value="3"/>
    <eLiterals name="thu" value="4"/>
    <eLiterals name="fri" value="5"/>
    <eLiterals name="sat" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Rental_hoursUser_typesValue">
    <eLiterals name="member"/>
    <eLiterals name="nonmember" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="system_hoursTypeValue">
    <eLiterals name="system_hours"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="system_hoursVersionValue">
    <eLiterals name="1.1-RC"/>
    <eLiterals name="1.1" value="1"/>
    <eLiterals name="2.0-RC" value="2"/>
    <eLiterals name="2.0" value="3"/>
    <eLiterals name="2.1-RC" value="4"/>
    <eLiterals name="2.1-RC2" value="5"/>
    <eLiterals name="2.1" value="6"/>
    <eLiterals name="2.2" value="7"/>
    <eLiterals name="3.0-RC" value="8"/>
    <eLiterals name="3.0" value="9"/>
  </eClassifiers>
</ecore:EPackage>
