/**
 */
package org.w3.ns.dcat;

import java.math.BigDecimal;

import javax.xml.datatype.Duration;

import org.eclipse.emf.common.util.EList;

import org.purl.dc.terms.terms.Location;
import org.purl.dc.terms.terms.PeriodOfTime;

import org.w3.ns.skos.Concept;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dataset Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * 
 *         dcat:Dataset represents a dataset. A dataset is a collection of data, published or curated by a single agent.
 *         Data comes in many forms including numbers, words, pixels, imagery, sound and other multi-media, and potentially
 *         other types, any of which might be collected into a dataset.
 *       
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getDistribution <em>Distribution</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getSpatialResolutionInMeters <em>Spatial Resolution In Meters</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getTemporalResolution <em>Temporal Resolution</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getAccrualPeriodicity <em>Accrual Periodicity</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getSpatial <em>Spatial</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getTemporal <em>Temporal</em>}</li>
 *   <li>{@link org.w3.ns.dcat.DatasetType#getWasGeneratedBy <em>Was Generated By</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.dcat.DcatPackage#getDatasetType()
 * @model extendedMetaData="name='DatasetType' kind='elementOnly'"
 * @generated
 */
public interface DatasetType extends ResourceType {
	/**
	 * Returns the value of the '<em><b>Distribution</b></em>' containment reference list.
	 * The list contents are of type {@link org.w3.ns.dcat.Distribution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Distribution</em>' containment reference list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_Distribution()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='distribution' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<Distribution> getDistribution();

	/**
	 * Returns the value of the '<em><b>Spatial Resolution In Meters</b></em>' attribute list.
	 * The list contents are of type {@link java.math.BigDecimal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Spatial Resolution In Meters</em>' attribute list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_SpatialResolutionInMeters()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.Decimal"
	 *        extendedMetaData="kind='element' name='spatialResolutionInMeters' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<BigDecimal> getSpatialResolutionInMeters();

	/**
	 * Returns the value of the '<em><b>Temporal Resolution</b></em>' attribute list.
	 * The list contents are of type {@link javax.xml.datatype.Duration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Temporal Resolution</em>' attribute list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_TemporalResolution()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.Duration"
	 *        extendedMetaData="kind='element' name='temporalResolution' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<Duration> getTemporalResolution();

	/**
	 * Returns the value of the '<em><b>Accrual Periodicity</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Accrual Periodicity</em>' containment reference.
	 * @see #setAccrualPeriodicity(Concept)
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_AccrualPeriodicity()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='accrualPeriodicity' namespace='http://purl.org/dc/terms/'"
	 * @generated
	 */
	Concept getAccrualPeriodicity();

	/**
	 * Sets the value of the '{@link org.w3.ns.dcat.DatasetType#getAccrualPeriodicity <em>Accrual Periodicity</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Accrual Periodicity</em>' containment reference.
	 * @see #getAccrualPeriodicity()
	 * @generated
	 */
	void setAccrualPeriodicity(Concept value);

	/**
	 * Returns the value of the '<em><b>Spatial</b></em>' containment reference list.
	 * The list contents are of type {@link org.purl.dc.terms.terms.Location}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Spatial</em>' containment reference list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_Spatial()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='spatial' namespace='http://purl.org/dc/terms/'"
	 * @generated
	 */
	EList<Location> getSpatial();

	/**
	 * Returns the value of the '<em><b>Temporal</b></em>' containment reference list.
	 * The list contents are of type {@link org.purl.dc.terms.terms.PeriodOfTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Temporal</em>' containment reference list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_Temporal()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='temporal' namespace='http://purl.org/dc/terms/'"
	 * @generated
	 */
	EList<PeriodOfTime> getTemporal();

	/**
	 * Returns the value of the '<em><b>Was Generated By</b></em>' attribute list.
	 * The list contents are of type {@link java.lang.String}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Generated By</em>' attribute list.
	 * @see org.w3.ns.dcat.DcatPackage#getDatasetType_WasGeneratedBy()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.AnyURI"
	 *        extendedMetaData="kind='element' name='wasGeneratedBy' namespace='http://www.w3.org/ns/prov#'"
	 * @generated
	 */
	EList<String> getWasGeneratedBy();

} // DatasetType
