/**
 */
package org.w3.ns.dcat.impl;

import de.dcatde.dcatde.Contributor;

import java.math.BigDecimal;

import java.util.Collection;

import javax.xml.datatype.Duration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.purl.dc.terms.terms.Location;
import org.purl.dc.terms.terms.PeriodOfTime;

import org.w3.ns.dcat.DatasetType;
import org.w3.ns.dcat.DcatPackage;
import org.w3.ns.dcat.Distribution;

import org.w3.ns.skos.Concept;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dataset Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getDistribution <em>Distribution</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getSpatialResolutionInMeters <em>Spatial Resolution In Meters</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getTemporalResolution <em>Temporal Resolution</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getAccrualPeriodicity <em>Accrual Periodicity</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getSpatial <em>Spatial</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getTemporal <em>Temporal</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getWasGeneratedBy <em>Was Generated By</em>}</li>
 *   <li>{@link org.w3.ns.dcat.impl.DatasetTypeImpl#getContributorId <em>Contributor Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DatasetTypeImpl extends ResourceTypeImpl implements DatasetType {
	/**
	 * The cached value of the '{@link #getDistribution() <em>Distribution</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDistribution()
	 * @generated
	 * @ordered
	 */
	protected EList<Distribution> distribution;

	/**
	 * The cached value of the '{@link #getSpatialResolutionInMeters() <em>Spatial Resolution In Meters</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSpatialResolutionInMeters()
	 * @generated
	 * @ordered
	 */
	protected EList<BigDecimal> spatialResolutionInMeters;

	/**
	 * The cached value of the '{@link #getTemporalResolution() <em>Temporal Resolution</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTemporalResolution()
	 * @generated
	 * @ordered
	 */
	protected EList<Duration> temporalResolution;

	/**
	 * The cached value of the '{@link #getAccrualPeriodicity() <em>Accrual Periodicity</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAccrualPeriodicity()
	 * @generated
	 * @ordered
	 */
	protected Concept accrualPeriodicity;

	/**
	 * The cached value of the '{@link #getSpatial() <em>Spatial</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSpatial()
	 * @generated
	 * @ordered
	 */
	protected EList<Location> spatial;

	/**
	 * The cached value of the '{@link #getTemporal() <em>Temporal</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTemporal()
	 * @generated
	 * @ordered
	 */
	protected EList<PeriodOfTime> temporal;

	/**
	 * The cached value of the '{@link #getWasGeneratedBy() <em>Was Generated By</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getWasGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected EList<String> wasGeneratedBy;

	/**
	 * The cached value of the '{@link #getContributorId() <em>Contributor Id</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getContributorId()
	 * @generated
	 * @ordered
	 */
	protected EList<Contributor> contributorId;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatasetTypeImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return DcatPackage.Literals.DATASET_TYPE;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Distribution> getDistribution() {
		if (distribution == null) {
			distribution = new EObjectContainmentEList<Distribution>(Distribution.class, this, DcatPackage.DATASET_TYPE__DISTRIBUTION);
		}
		return distribution;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<BigDecimal> getSpatialResolutionInMeters() {
		if (spatialResolutionInMeters == null) {
			spatialResolutionInMeters = new EDataTypeEList<BigDecimal>(BigDecimal.class, this, DcatPackage.DATASET_TYPE__SPATIAL_RESOLUTION_IN_METERS);
		}
		return spatialResolutionInMeters;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Duration> getTemporalResolution() {
		if (temporalResolution == null) {
			temporalResolution = new EDataTypeEList<Duration>(Duration.class, this, DcatPackage.DATASET_TYPE__TEMPORAL_RESOLUTION);
		}
		return temporalResolution;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Concept getAccrualPeriodicity() {
		return accrualPeriodicity;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetAccrualPeriodicity(Concept newAccrualPeriodicity, NotificationChain msgs) {
		Concept oldAccrualPeriodicity = accrualPeriodicity;
		accrualPeriodicity = newAccrualPeriodicity;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY, oldAccrualPeriodicity, newAccrualPeriodicity);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setAccrualPeriodicity(Concept newAccrualPeriodicity) {
		if (newAccrualPeriodicity != accrualPeriodicity) {
			NotificationChain msgs = null;
			if (accrualPeriodicity != null)
				msgs = ((InternalEObject)accrualPeriodicity).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY, null, msgs);
			if (newAccrualPeriodicity != null)
				msgs = ((InternalEObject)newAccrualPeriodicity).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY, null, msgs);
			msgs = basicSetAccrualPeriodicity(newAccrualPeriodicity, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY, newAccrualPeriodicity, newAccrualPeriodicity));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Location> getSpatial() {
		if (spatial == null) {
			spatial = new EObjectContainmentEList<Location>(Location.class, this, DcatPackage.DATASET_TYPE__SPATIAL);
		}
		return spatial;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<PeriodOfTime> getTemporal() {
		if (temporal == null) {
			temporal = new EObjectContainmentEList<PeriodOfTime>(PeriodOfTime.class, this, DcatPackage.DATASET_TYPE__TEMPORAL);
		}
		return temporal;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<String> getWasGeneratedBy() {
		if (wasGeneratedBy == null) {
			wasGeneratedBy = new EDataTypeEList<String>(String.class, this, DcatPackage.DATASET_TYPE__WAS_GENERATED_BY);
		}
		return wasGeneratedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Contributor> getContributorId() {
		if (contributorId == null) {
			contributorId = new EObjectResolvingEList<Contributor>(Contributor.class, this, DcatPackage.DATASET_TYPE__CONTRIBUTOR_ID);
		}
		return contributorId;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case DcatPackage.DATASET_TYPE__DISTRIBUTION:
				return ((InternalEList<?>)getDistribution()).basicRemove(otherEnd, msgs);
			case DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY:
				return basicSetAccrualPeriodicity(null, msgs);
			case DcatPackage.DATASET_TYPE__SPATIAL:
				return ((InternalEList<?>)getSpatial()).basicRemove(otherEnd, msgs);
			case DcatPackage.DATASET_TYPE__TEMPORAL:
				return ((InternalEList<?>)getTemporal()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case DcatPackage.DATASET_TYPE__DISTRIBUTION:
				return getDistribution();
			case DcatPackage.DATASET_TYPE__SPATIAL_RESOLUTION_IN_METERS:
				return getSpatialResolutionInMeters();
			case DcatPackage.DATASET_TYPE__TEMPORAL_RESOLUTION:
				return getTemporalResolution();
			case DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY:
				return getAccrualPeriodicity();
			case DcatPackage.DATASET_TYPE__SPATIAL:
				return getSpatial();
			case DcatPackage.DATASET_TYPE__TEMPORAL:
				return getTemporal();
			case DcatPackage.DATASET_TYPE__WAS_GENERATED_BY:
				return getWasGeneratedBy();
			case DcatPackage.DATASET_TYPE__CONTRIBUTOR_ID:
				return getContributorId();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case DcatPackage.DATASET_TYPE__DISTRIBUTION:
				getDistribution().clear();
				getDistribution().addAll((Collection<? extends Distribution>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__SPATIAL_RESOLUTION_IN_METERS:
				getSpatialResolutionInMeters().clear();
				getSpatialResolutionInMeters().addAll((Collection<? extends BigDecimal>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__TEMPORAL_RESOLUTION:
				getTemporalResolution().clear();
				getTemporalResolution().addAll((Collection<? extends Duration>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY:
				setAccrualPeriodicity((Concept)newValue);
				return;
			case DcatPackage.DATASET_TYPE__SPATIAL:
				getSpatial().clear();
				getSpatial().addAll((Collection<? extends Location>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__TEMPORAL:
				getTemporal().clear();
				getTemporal().addAll((Collection<? extends PeriodOfTime>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__WAS_GENERATED_BY:
				getWasGeneratedBy().clear();
				getWasGeneratedBy().addAll((Collection<? extends String>)newValue);
				return;
			case DcatPackage.DATASET_TYPE__CONTRIBUTOR_ID:
				getContributorId().clear();
				getContributorId().addAll((Collection<? extends Contributor>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case DcatPackage.DATASET_TYPE__DISTRIBUTION:
				getDistribution().clear();
				return;
			case DcatPackage.DATASET_TYPE__SPATIAL_RESOLUTION_IN_METERS:
				getSpatialResolutionInMeters().clear();
				return;
			case DcatPackage.DATASET_TYPE__TEMPORAL_RESOLUTION:
				getTemporalResolution().clear();
				return;
			case DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY:
				setAccrualPeriodicity((Concept)null);
				return;
			case DcatPackage.DATASET_TYPE__SPATIAL:
				getSpatial().clear();
				return;
			case DcatPackage.DATASET_TYPE__TEMPORAL:
				getTemporal().clear();
				return;
			case DcatPackage.DATASET_TYPE__WAS_GENERATED_BY:
				getWasGeneratedBy().clear();
				return;
			case DcatPackage.DATASET_TYPE__CONTRIBUTOR_ID:
				getContributorId().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case DcatPackage.DATASET_TYPE__DISTRIBUTION:
				return distribution != null && !distribution.isEmpty();
			case DcatPackage.DATASET_TYPE__SPATIAL_RESOLUTION_IN_METERS:
				return spatialResolutionInMeters != null && !spatialResolutionInMeters.isEmpty();
			case DcatPackage.DATASET_TYPE__TEMPORAL_RESOLUTION:
				return temporalResolution != null && !temporalResolution.isEmpty();
			case DcatPackage.DATASET_TYPE__ACCRUAL_PERIODICITY:
				return accrualPeriodicity != null;
			case DcatPackage.DATASET_TYPE__SPATIAL:
				return spatial != null && !spatial.isEmpty();
			case DcatPackage.DATASET_TYPE__TEMPORAL:
				return temporal != null && !temporal.isEmpty();
			case DcatPackage.DATASET_TYPE__WAS_GENERATED_BY:
				return wasGeneratedBy != null && !wasGeneratedBy.isEmpty();
			case DcatPackage.DATASET_TYPE__CONTRIBUTOR_ID:
				return contributorId != null && !contributorId.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (spatialResolutionInMeters: ");
		result.append(spatialResolutionInMeters);
		result.append(", temporalResolution: ");
		result.append(temporalResolution);
		result.append(", wasGeneratedBy: ");
		result.append(wasGeneratedBy);
		result.append(')');
		return result.toString();
	}

} //DatasetTypeImpl
