version: '2'

services:

    mongo01:
        image: mongo:latest
        entrypoint: [ "/usr/bin/mongod", "--dbpath", "/data", "--journal", "--bind_ip", "0.0.0.0"]
        ports:
            - "27017:27017"

#    de.jena:
#        image: mdo/de.jena:latest
#        ports:
#            - "8080:8080"

