<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xmla" nsURI="urn:schemas-microsoft-com:xml-analysis" nsPrefix="_xmla">
  <eAnnotations source="https://jakarta.ee/xml/ns/jaxb">
    <details key="version" value="3.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="_xmla_empty" value="xmla_empty.ecore#/"/>
    <details key="_xmla_mddataset" value="xmla_mddataset.ecore#/"/>
    <details key="_xmla_multipleresults" value="xmla_multipleresults.ecore#/"/>
    <details key="_xmla_rowset" value="xmla_rowset.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoverResponse">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DiscoverResponse_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="#//Return"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="return"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discover">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Discover_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestType" lowerBound="1"
        eType="#//Request" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="RequestType"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictions" lowerBound="1"
        eType="#//Restrictions" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Restrictions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="#//Properties" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Properties"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Properties">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Properties"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyList" eType="#//PropertyList"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="PropertyList"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyList">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PropertyList"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSourceInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DataSourceInfo"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Timeout"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="UserName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Password"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localeIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="LocaleIdentifier"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Catalog"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateSupport" eType="#//StateSupport"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="StateSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="#//Content"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Content"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Format"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axisFormat" eType="#//AxisFormat"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="AxisFormat"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beginRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="BeginRange"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="EndRange"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mDXSupport" eType="#//MDXSupport"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MDXSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ProviderName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ProviderVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dBMSVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DBMSVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerType" eType="#//ProviderType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ProviderType"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showHiddenCubes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ShowHiddenCubes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sQLSupport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SQLSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionDDL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="TransactionDDL"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumRows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MaximumRows"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Roles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualMode" eType="#//VisualMode"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="VisualMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveRoles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="EffectiveRoles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveUserName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="EffectiveUserName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ServerName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalogLocation" eType="#//CatalogLocation"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CatalogLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropCatalogTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropCatalogTerm"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropCatalogUsage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropCatalogUsage"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropColumnDefinition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropColumnDefinition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropConcatNullBehavior"
        eType="#//DbpropConcatNullBehavior" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropConcatNullBehavior"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropDataSourceReadOnly"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropDataSourceReadOnly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropGroupBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropGroupBy"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropHeterogeneousTables"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropHeterogeneousTables"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropIdentifierCase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropIdentifierCase"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMaxIndexSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMaxIndexSize"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMaxOpenChapters"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMaxOpenChapters"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMaxRowSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMaxRowSize"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMaxRowSizeIncludeBlob"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMaxRowSizeIncludeBlob"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMaxTablesInSelect"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMaxTablesInSelect"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMultiTableUpdate"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMultiTableUpdate"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropNullCollation" eType="#//DbpropNullCollation"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropNullCollation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropOrderByColumnsInSelect"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropOrderByColumnsInSelect"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropOutputParameterAvailable"
        eType="#//DbpropOutputParameterAvailable" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropOutputParameterAvailable"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropPersistentIdType"
        eType="#//DbpropPersistentIdType" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropPersistentIdType"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropPrepareAbortBehavior"
        eType="#//DbpropPrepareAbortBehavior" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropPrepareAbortBehavior"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropPrepareCommitBehavior"
        eType="#//DbpropPrepareCommitBehavior" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropPrepareCommitBehavior"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropProcedureTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropProcedureTerm"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropQuotedIdentifierCase"
        eType="#//DbpropQuotedIdentifierCase" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropQuotedIdentifierCase"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSchemaUsage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSchemaUsage"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSqlSupport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSqlSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSubqueries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSubqueries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSupportedTxnDdl"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSupportedTxnDdl"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxSubqueries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxSubqueries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSupportedTxnIsoLevels"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSupportedTxnIsoLevels"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropSupportedTxnIsoRetain"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropSupportedTxnIsoRetain"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropTableTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropTableTerm"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropAggregateCellUpdate"
        eType="#//MdpropAggregateCellUpdate" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropAggregateCellUpdate"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropAxes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropAxes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropFlatteningSupport"
        eType="#//MdpropFlatteningSupport" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropFlatteningSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxCaseSupport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxCaseSupport"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxDescFlags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxDescFlags"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxDrillFunctions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxDrillFunctions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxFormulas" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxFormulas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxJoinCubes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxJoinCubes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxMemberFunctions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxMemberFunctions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxNonMeasureExpressions"
        eType="#//MdpropMdxNonMeasureExpressions" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxNonMeasureExpressions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxNumericFunctions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxNumericFunctions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxObjQualification"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxObjQualification"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxOuterReference"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxOuterReference"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxQueryByProperty"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxQueryByProperty"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxRangeRowset" eType="#//MdpropMdxRangeRowset"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxRangeRowset"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxSetFunctions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxSetFunctions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxSlicer" eType="#//MdpropMdxSlicer"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxSlicer"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxStringCompop"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxStringCompop"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropNamedLevels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropNamedLevels"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdMDXCompatibility"
        eType="#//DbpropMsmdMDXCompatibility" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdMDXCompatibility"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdSQLCompatibility"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdSQLCompatibility"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdMDXUniqueNameStyle"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdMDXUniqueNameStyle"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCachePolicy"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCachePolicy"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCacheRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCacheRatio"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCacheMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCacheMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCompareCaseSensitiveStringFlags"
        eType="#//DbpropMsmdCompareCaseSensitiveStringFlags" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCompareCaseSensitiveStringFlags"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCompareCaseNotSensitiveStringFlags"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCompareCaseNotSensitiveStringFlags"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdFlattened2" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdFlattened2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropInitMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropInitMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sspropInitAppName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SspropInitAppName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sspropInitWsid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SspropInitWsid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sspropInitPacketsize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SspropInitPacketsize"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnlySession" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ReadOnlySession"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securedCellValue" eType="#//SecuredCellValue"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SecuredCellValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonEmptyThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="NonEmptyThreshold"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safetyOptions" eType="#//SafetyOptions"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SafetyOptions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdCacheRatio2"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdCacheRatio2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdUseFormulaCache"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdUseFormulaCache"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdDynamicDebugLimit"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdDynamicDebugLimit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdDebugMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdDebugMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dialect" eType="#//Dialect"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Dialect"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactAnalysis" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ImpactAnalysis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sQLQueryMode" eType="#//SQLQueryMode"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="SQLQueryMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientProcessID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ClientProcessID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cube" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Cube"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnCellProperties" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ReturnCellProperties"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commitTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CommitTimeout"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forceCommitTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ForceCommitTimeout"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ExecutionMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realTimeOlap" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="RealTimeOlap"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdxMissingMemberMode" eType="#//MdxMissingMemberMode"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdxMissingMemberMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxNamedSets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxNamedSets"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdSubqueries" eType="#//DbpropMsmdSubqueries"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdSubqueries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdAutoExists" eType="#//DbpropMsmdAutoExists"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdAutoExists"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CustomData"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disablePrefetchFacts" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DisablePrefetchFacts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateIsolationLevel" eType="#//UpdateIsolationLevel"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="UpdateIsolationLevel"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdErrorMessageMode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdErrorMessageMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdpropMdxDdlExtensions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MdpropMdxDdlExtensions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseEncoding" eType="#//ResponseEncoding"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ResponseEncoding"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryLockingMode" eType="#//MemoryLockingMode"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="MemoryLockingMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdOptimizeResponse"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdOptimizeResponse"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdActivityID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdActivityID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdRequestID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdRequestID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnAffectedObjects"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ReturnAffectedObjects"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbpropMsmdRequestMemoryLimit"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DbpropMsmdRequestMemoryLimit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationContext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ApplicationContext"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Request">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="RequestType_._type"/>
    </eAnnotations>
    <eLiterals name="DBSCHEMACATALOGS" literal="DBSCHEMA_CATALOGS"/>
    <eLiterals name="MDSCHEMACUBES" value="1" literal="MDSCHEMA_CUBES"/>
    <eLiterals name="MDSCHEMADIMENSIONS" value="2" literal="MDSCHEMA_DIMENSIONS"/>
    <eLiterals name="MDSCHEMAHIERARCHIES" value="3" literal="MDSCHEMA_HIERARCHIES"/>
    <eLiterals name="MDSCHEMALEVELS" value="4" literal="MDSCHEMA_LEVELS"/>
    <eLiterals name="MDSCHEMAMEASURES" value="5" literal="MDSCHEMA_MEASURES"/>
    <eLiterals name="MDSCHEMAPROPERTIES" value="6" literal="MDSCHEMA_PROPERTIES"/>
    <eLiterals name="MDSCHEMAMEMBERS" value="7" literal="MDSCHEMA_MEMBERS"/>
    <eLiterals name="MDSCHEMAACTIONS" value="8" literal="MDSCHEMA_ACTIONS"/>
    <eLiterals name="MDSCHEMASETS" value="9" literal="MDSCHEMA_SETS"/>
    <eLiterals name="DISCOVERINSTANCES" value="10" literal="DISCOVER_INSTANCES"/>
    <eLiterals name="MDSCHEMAKPIS" value="11" literal="MDSCHEMA_KPIS"/>
    <eLiterals name="MDSCHEMAMEASUREGROUPS" value="12" literal="MDSCHEMA_MEASUREGROUPS"/>
    <eLiterals name="MDSCHEMAMEASUREGROUPDIMENSIONS" value="13" literal="MDSCHEMA_MEASUREGROUP_DIMENSIONS"/>
    <eLiterals name="DISCOVERPROPERTIES" value="14" literal="DISCOVER_PROPERTIES"/>
    <eLiterals name="DISCOVERLITERALS" value="15" literal="DISCOVER_LITERALS"/>
    <eLiterals name="DISCOVERSCHEMAROWSETS" value="16" literal="DISCOVER_SCHEMA_ROWSETS"/>
    <eLiterals name="DISCOVERKEYWORDS" value="17" literal="DISCOVER_KEYWORDS"/>
    <eLiterals name="DBSCHEMATABLES" value="18" literal="DBSCHEMA_TABLES"/>
    <eLiterals name="DBSCHEMACOLUMNS" value="19" literal="DBSCHEMA_COLUMNS"/>
    <eLiterals name="DBSCHEMAPROVIDERTYPES" value="20" literal="DBSCHEMA_PROVIDER_TYPES"/>
    <eLiterals name="MDSCHEMAINPUTDATASOURCES" value="21" literal="MDSCHEMA_INPUT_DATASOURCES"/>
    <eLiterals name="DMSCHEMAMININGSERVICES" value="22" literal="DMSCHEMA_MINING_SERVICES"/>
    <eLiterals name="DMSCHEMAMININGSERVICEPARAMETERS" value="23" literal="DMSCHEMA_MINING_SERVICE_PARAMETERS"/>
    <eLiterals name="DMSCHEMAMININGFUNCTIONS" value="24" literal="DMSCHEMA_MINING_FUNCTIONS"/>
    <eLiterals name="DMSCHEMAMININGMODELCONTENT" value="25" literal="DMSCHEMA_MINING_MODEL_CONTENT"/>
    <eLiterals name="DMSCHEMAMININGMODELXML" value="26" literal="DMSCHEMA_MINING_MODEL_XML"/>
    <eLiterals name="DMSCHEMAMININGMODELCONTENTPMML" value="27" literal="DMSCHEMA_MINING_MODEL_CONTENT_PMML"/>
    <eLiterals name="DMSCHEMAMININGMODELS" value="28" literal="DMSCHEMA_MINING_MODELS"/>
    <eLiterals name="DMSCHEMAMININGCOLUMNS" value="29" literal="DMSCHEMA_MINING_COLUMNS"/>
    <eLiterals name="DMSCHEMAMININGSTRUCTURES" value="30" literal="DMSCHEMA_MINING_STRUCTURES"/>
    <eLiterals name="DMSCHEMAMININGSTRUCTURECOLUMNS" value="31" literal="DMSCHEMA_MINING_STRUCTURE_COLUMNS"/>
    <eLiterals name="DISCOVERDATASOURCES" value="32" literal="DISCOVER_DATASOURCES"/>
    <eLiterals name="DISCOVERENUMERATORS" value="33" literal="DISCOVER_ENUMERATORS"/>
    <eLiterals name="DISCOVERXMLMETADATA" value="34" literal="DISCOVER_XML_METADATA"/>
    <eLiterals name="DISCOVERTRACES" value="35" literal="DISCOVER_TRACES"/>
    <eLiterals name="DISCOVERTRACEDEFINITIONPROVIDERINFO" value="36" literal="DISCOVER_TRACE_DEFINITION_PROVIDERINFO"/>
    <eLiterals name="DISCOVERTRACECOLUMNS" value="37" literal="DISCOVER_TRACE_COLUMNS"/>
    <eLiterals name="DISCOVERTRACEEVENTCATEGORIES" value="38" literal="DISCOVER_TRACE_EVENT_CATEGORIES"/>
    <eLiterals name="DISCOVERMEMORYUSAGE" value="39" literal="DISCOVER_MEMORYUSAGE"/>
    <eLiterals name="DISCOVERMEMORYGRANT" value="40" literal="DISCOVER_MEMORYGRANT"/>
    <eLiterals name="DISCOVERLOCKS" value="41" literal="DISCOVER_LOCKS"/>
    <eLiterals name="DISCOVERCONNECTIONS" value="42" literal="DISCOVER_CONNECTIONS"/>
    <eLiterals name="DISCOVERSESSIONS" value="43" literal="DISCOVER_SESSIONS"/>
    <eLiterals name="DISCOVERJOBS" value="44" literal="DISCOVER_JOBS"/>
    <eLiterals name="DISCOVERTRANSACTIONS" value="45" literal="DISCOVER_TRANSACTIONS"/>
    <eLiterals name="DISCOVERDBCONNECTIONS" value="46" literal="DISCOVER_DB_CONNECTIONS"/>
    <eLiterals name="DISCOVERMASTERKEY" value="47" literal="DISCOVER_MASTER_KEY"/>
    <eLiterals name="DISCOVERPERFORMANCECOUNTERS" value="48" literal="DISCOVER_PERFORMANCE_COUNTERS"/>
    <eLiterals name="DISCOVERLOCATIONS" value="49" literal="DISCOVER_LOCATIONS"/>
    <eLiterals name="DISCOVERPARTITIONDIMENSIONSTAT" value="50" literal="DISCOVER_PARTITION_DIMENSION_STAT"/>
    <eLiterals name="DISCOVERPARTITIONSTAT" value="51" literal="DISCOVER_PARTITION_STAT"/>
    <eLiterals name="DISCOVERDIMENSIONSTAT" value="52" literal="DISCOVER_DIMENSION_STAT"/>
    <eLiterals name="DISCOVERCOMMANDS" value="53" literal="DISCOVER_COMMANDS"/>
    <eLiterals name="DISCOVERCOMMANDOBJECTS" value="54" literal="DISCOVER_COMMAND_OBJECTS"/>
    <eLiterals name="DISCOVEROBJECTACTIVITY" value="55" literal="DISCOVER_OBJECT_ACTIVITY"/>
    <eLiterals name="DISCOVEROBJECTMEMORYUSAGE" value="56" literal="DISCOVER_OBJECT_MEMORY_USAGE"/>
    <eLiterals name="DISCOVERSTORAGETABLES" value="57" literal="DISCOVER_STORAGE_TABLES"/>
    <eLiterals name="DISCOVERSTORAGETABLECOLUMNS" value="58" literal="DISCOVER_STORAGE_TABLE_COLUMNS"/>
    <eLiterals name="DISCOVERSTORAGETABLECOLUMNSEGMENTS" value="59" literal="DISCOVER_STORAGE_TABLE_COLUMN_SEGMENTS"/>
    <eLiterals name="DISCOVERCSDLMETADATA" value="60" literal="DISCOVER_CSDL_METADATA"/>
    <eLiterals name="DISCOVERCALCDEPENDENCY" value="61" literal="DISCOVER_CALC_DEPENDENCY"/>
    <eLiterals name="MDSCHEMAFUNCTIONS" value="62" literal="MDSCHEMA_FUNCTIONS"/>
    <eLiterals name="DISCOVERRINGBUFFERS" value="63" literal="DISCOVER_RING_BUFFERS"/>
    <eLiterals name="DISCOVERXEVENTTRACEDEFINITION" value="64" literal="DISCOVER_XEVENT_TRACE_DEFINITION"/>
    <eLiterals name="DISCOVERXEVENTPACKAGES" value="65" literal="DISCOVER_XEVENT_PACKAGES"/>
    <eLiterals name="DISCOVERXEVENTOBJECTS" value="66" literal="DISCOVER_XEVENT_OBJECTS"/>
    <eLiterals name="DISCOVERXEVENTOBJECTCOLUMNS" value="67" literal="DISCOVER_XEVENT_OBJECT_COLUMNS"/>
    <eLiterals name="DISCOVERXEVENTSESSIONS" value="68" literal="DISCOVER_XEVENT_SESSIONS"/>
    <eLiterals name="DISCOVERXEVENTSESSIONTARGETS" value="69" literal="DISCOVER_XEVENT_SESSION_TARGETS"/>
    <eLiterals name="DISCOVERMEMSTATS" value="70" literal="DISCOVER_MEM_STATS"/>
    <eLiterals name="DISCOVERDBMEMSTATS" value="71" literal="DISCOVER_DB_MEM_STATS"/>
    <eLiterals name="DISCOVEROBJECTCOUNTERS" value="72" literal="DISCOVER_OBJECT_COUNTERS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResponseEncoding">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ResponseEncoding_._type"/>
    </eAnnotations>
    <eLiterals name="Default"/>
    <eLiterals name="UTF8" value="1" literal="UTF-8"/>
    <eLiterals name="UTF16" value="2" literal="UTF-16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestrictionList">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="RestrictionList_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="wildcards" value="##any"/>
        <details key="name" value=":0"/>
        <details key="processing" value="strict"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restrictions">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Restrictions_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictionList" eType="#//RestrictionList"
        unsettable="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="RestrictionList"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="return"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="ecore:EClass xmla_mddataset.ecore#//Mddataset"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="root"/>
        <details key="namespace" value="urn:schemas-microsoft-com:xml-analysis:mddataset"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root1" eType="ecore:EClass xmla_rowset.ecore#//Rowset"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="root"/>
        <details key="namespace" value="urn:schemas-microsoft-com:xml-analysis:rowset"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root2" eType="ecore:EClass xmla_empty.ecore#//Emptyresult"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="root"/>
        <details key="namespace" value="urn:schemas-microsoft-com:xml-analysis:empty"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" eType="ecore:EClass xmla_multipleresults.ecore#//ResultsType"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="results"/>
        <details key="namespace" value="http://schemas.microsoft.com/analysisservices/2003/xmla-multipleresults"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateSupport">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StateSupport_._type"/>
    </eAnnotations>
    <eLiterals name="None"/>
    <eLiterals name="Sessions" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Format">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Format_._1_._type"/>
    </eAnnotations>
    <eLiterals name="Tabular"/>
    <eLiterals name="Multidimensional" value="1"/>
    <eLiterals name="Native" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Content">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Content_._1_._type"/>
    </eAnnotations>
    <eLiterals name="None"/>
    <eLiterals name="Schema" value="1"/>
    <eLiterals name="Data" value="2"/>
    <eLiterals name="SchemaData" value="3"/>
    <eLiterals name="Metadata" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisFormat">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AxisFormat_._type"/>
    </eAnnotations>
    <eLiterals name="ClusterFormat"/>
    <eLiterals name="CustomFormat" value="1"/>
    <eLiterals name="TupleFormat" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MDXSupport">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MDXSupport_._type"/>
    </eAnnotations>
    <eLiterals name="Core"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProviderType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ProviderType_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_3" value="2" literal="3"/>
    <eLiterals name="_4" value="3" literal="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisualMode">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VisualMode_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CatalogLocation">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CatalogLocation_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropConcatNullBehavior">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropConcatNullBehavior_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropNullCollation">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropNullCollation_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_4" value="2" literal="4"/>
    <eLiterals name="_8" value="3" literal="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropOutputParameterAvailable">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropOutputParameterAvailable_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_4" value="2" literal="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropPersistentIdType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropPersistentIdType_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_4" value="2" literal="4"/>
    <eLiterals name="_8" value="3" literal="8"/>
    <eLiterals name="_16" value="4" literal="16"/>
    <eLiterals name="_32" value="5" literal="32"/>
    <eLiterals name="_64" value="6" literal="64"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropPrepareAbortBehavior">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropPrepareAbortBehavior_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropPrepareCommitBehavior">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropPrepareCommitBehavior_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropQuotedIdentifierCase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropQuotedIdentifierCase_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_4" value="2" literal="4"/>
    <eLiterals name="_8" value="3" literal="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdpropAggregateCellUpdate">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdpropAggregateCellUpdate_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdpropFlatteningSupport">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdpropFlatteningSupport_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_3" value="2" literal="3"/>
    <eLiterals name="_4" value="3" literal="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdpropMdxNonMeasureExpressions">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdpropMdxNonMeasureExpressions_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdpropMdxRangeRowset">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdpropMdxRangeRowset_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_4" value="2" literal="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdpropMdxSlicer">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdpropMdxSlicer_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdxMissingMemberMode">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MdxMissingMemberMode_._type"/>
    </eAnnotations>
    <eLiterals name="Default"/>
    <eLiterals name="Ignore" value="1"/>
    <eLiterals name="Error" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropMsmdMDXCompatibility">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropMsmdMDXCompatibility_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropMsmdCompareCaseSensitiveStringFlags">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropMsmdCompareCaseSensitiveStringFlags_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
    <eLiterals name="_16" value="2" literal="16"/>
    <eLiterals name="_256" value="3" literal="256"/>
    <eLiterals name="_4096" value="4" literal="4096"/>
    <eLiterals name="_65536" value="5" literal="65536"/>
    <eLiterals name="_1048576" value="6" literal="1048576"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecuredCellValue">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SecuredCellValue_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
    <eLiterals name="_4" value="4" literal="4"/>
    <eLiterals name="_5" value="5" literal="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SafetyOptions">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SafetyOptions_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dialect">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Dialect_._type"/>
    </eAnnotations>
    <eLiterals name="MDX"/>
    <eLiterals name="DMX" value="1"/>
    <eLiterals name="SQL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SQLQueryMode">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SQLQueryMode_._type"/>
    </eAnnotations>
    <eLiterals name="Data"/>
    <eLiterals name="Calculated" value="1"/>
    <eLiterals name="IncludeEmpty" value="2"/>
    <eLiterals name="DataKeys" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropMsmdSubqueries">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropMsmdSubqueries_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DbpropMsmdAutoExists">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DbpropMsmdAutoExists_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
    <eLiterals name="_2" value="2" literal="2"/>
    <eLiterals name="_3" value="3" literal="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UpdateIsolationLevel">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="UpdateIsolationLevel_._type"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1"/>
    <eLiterals name="_2" value="1" literal="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MemoryLockingMode">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MemoryLockingMode_._type"/>
    </eAnnotations>
    <eLiterals name="_0"/>
    <eLiterals name="_1" value="1" literal="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Visibility_._type"/>
    </eAnnotations>
    <eLiterals name="SchemaRowset"/>
    <eLiterals name="None" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Annotation"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Visibility"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Value"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotations">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Annotations_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" upperBound="-1"
        eType="#//Annotation" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Annotation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" abstract="true">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Binding"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventSession">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="event_session_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="templateCategory"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="templateName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="templateDescription"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"
        resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="event"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"
        resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="target"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dispatchLatency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"
        defaultValueLiteral="30" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="dispatchLatency"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventRetentionMode" eType="#//RetentionModes"
        defaultValueLiteral="allowSingleEventLoss" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="eventRetentionMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEventSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"
        defaultValueLiteral="0" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="maxEventSize"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedLong"
        defaultValueLiteral="4" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="maxMemory"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryPartitionMode" eType="#//PartitionModes"
        defaultValueLiteral="none" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="memoryPartitionMode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackCausality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="trackCausality"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RetentionModes">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="retentionModes"/>
    </eAnnotations>
    <eLiterals name="allowSingleEventLoss"/>
    <eLiterals name="allowMultipleEventLoss" value="1"/>
    <eLiterals name="noEventLoss" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PartitionModes">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="partitionModes"/>
    </eAnnotations>
    <eLiterals name="none"/>
    <eLiterals name="perNode" value="1"/>
    <eLiterals name="perCpu" value="2"/>
  </eClassifiers>
</ecore:EPackage>
