<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="asset" nsURI="http://udp.jena.de/asset/1.0" nsPrefix="asset">
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//Asset #//Adressable #//PhysicalAsset #//TechnicalAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildingMetaData" lowerBound="1"
        eType="#//BuildingMetaData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adress">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="district" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="streetNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="streetNumberExt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifyer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leadingDataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leadingDataSourceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//Identifyer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adressable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//Adress"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalAsset" eSuperTypes="#//Asset #//PhysicalAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="technicalAssetMetaData"
        eType="#//TechnicalAssetMetaData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildingMetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monumentConservation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="barrierFree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geometry" eType="#//Geometry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Geometry" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalAsset" abstract="true" interface="true"
      eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="geoLocation" eType="#//GeoLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalAssetMetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
