<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gbfs_versions" nsURI="http://smartmodels.com/gbfs_versions/1.0"
    nsPrefix="gbfs_versions">
  <eClassifiers xsi:type="ecore:EClass" name="gbfs_versions">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Lists all feed endpoints published according to version sof the GBFS documentation. (added in v1.1) According to the Standard GBFS 2.2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Response data in the form of name:value pairs."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unique identifier of the entity"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_updated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Last time the data in the feed was updated in POSIX time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ttl" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//gbfs_versionsTypeValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NGSI entity type. It has to be gbfs_versions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="#//gbfs_versionsVersionValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GBFS version number to which the feed conforms, according to the versioning framework."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Response data in the form of name:value pairs."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//Versions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Versions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="URL of the corresponding gbfs.json endpoint"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="#//VersionsVersionValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The semantic version of the feed in the form X.Y"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VersionsVersionValue">
    <eLiterals name="1.1-RC"/>
    <eLiterals name="1.1" value="1"/>
    <eLiterals name="2.0-RC" value="2"/>
    <eLiterals name="2.0" value="3"/>
    <eLiterals name="2.1-RC" value="4"/>
    <eLiterals name="2.1-RC2" value="5"/>
    <eLiterals name="2.1" value="6"/>
    <eLiterals name="2.2" value="7"/>
    <eLiterals name="3.0-RC" value="8"/>
    <eLiterals name="3.0" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="gbfs_versionsTypeValue">
    <eLiterals name="gbfs_versions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="gbfs_versionsVersionValue">
    <eLiterals name="1.1-RC"/>
    <eLiterals name="1.1" value="1"/>
    <eLiterals name="2.0-RC" value="2"/>
    <eLiterals name="2.0" value="3"/>
    <eLiterals name="2.1-RC" value="4"/>
    <eLiterals name="2.1" value="5"/>
    <eLiterals name="2.2" value="6"/>
    <eLiterals name="3.0-RC" value="7"/>
    <eLiterals name="3.0" value="8"/>
  </eClassifiers>
</ecore:EPackage>
